const mongoose = require("mongoose");
// const db = require("../models");
const Suspect = require("../models/suspects");

// This file empties the Suspects collection and inserts the suspects below

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/suspects",
  //process.env.MONGODB_URI || "mongodb+srv://root:root12345@cluster0.1t27v.mongodb.net/myFirstDatabase?retryWrites=true&w=majoritygit",
  //"mongodb+srv://root:root12345@cluster0.1t27v.mongodb.net/suspects?retryWrites=true&w=majority" || 'mongodb://localhost/suspects',
  { useNewUrlParser: true, 
    useUnifiedTopology: true,
    useCreateIndex: true,
    useFindAndModify: false
}
);

const suspectSeed = [
  {
    id: "1",
    name: "linda pearl",
    age: "30",
    sex: "female",
    height: "165",
    weight: "70",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "narrow lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "asian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "short",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/1-linda-pearl.jpeg",
  },

  {
    id: "2",
    name: "lorna james",
    age: "30",
    sex: "female",
    height: "165",
    weight: "70",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/2-lorna-james.jpeg",
  },

  {
    id: "3",
    name: "billie Kidd",
    age: "45",
    sex: "male",
    height: "180",
    weight: "75",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/3-billie-kidd.jpeg",
  },

  {
    id: "4",
    name: "elli belle",
    age: "40",
    sex: "female",
    height: "173",
    weight: "80",
    hairType: "curly",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "soft arch",
    noseShape: "hooked",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "short ",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/4-elli-belle.jpeg",
  },

  {
    id: "5",
    name: "allan sutton",
    age: "45",
    sex: "male",
    height: "180",
    weight: "73",
    hairType: "curly",
    hairColour: "brown",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "curved",
    noseShape: "grecian",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "short",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "no",
    image: "/img/5-allan-sutton.jpeg",
  },

  {
    id: "6",
    name: "John Doe",
    age: "50",
    sex: "male",
    height: "185",
    weight: "90",
    hairType: "straight",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "curved",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "yes",
    image: "/img/6-john-doe.jpeg",
  },
  {
    id: "7",
    name: "rafa fraka",
    age: "48",
    sex: "male",
    height: "190",
    weight: "87",
    hairType: "curly",
    hairColour: "black",
    hairLength: "medium ",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "high arch",
    noseShape: "roman",
    race: "latino",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "square",
    neck: "long",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "yes",
    image: "/img/7-rafa-fraka.jpeg",
  },

  {
    id: "8",
    name: "curtis jackson",
    age: "30",
    sex: "male",
    height: "176",
    weight: "80",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "black skin",
    scars: "no",
    tattoos: "no",
    earShape: "pointed ear",
    eyebrowsShape: "curved",
    noseShape: "button",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/8-curtis-jackson.jpeg",
  },
  {
    id: "9",
    name: "bill gates",
    age: "29",
    sex: "male",
    height: "175",
    weight: "63",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "round lobe",
    eyebrowsShape: "soft arch",
    noseShape: "roman",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/9-bill-gates.jpeg",
  },
  {
    id: "10",
    name: "bonnie parker",
    age: "20",
    sex: "male",
    height: "166",
    weight: "72",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "pointed ear",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/10-bonnie_parker.jpeg",
  },
  {
    id: "11",
    name: "bridge higgins",
    age: "28",
    sex: "female",
    height: "183",
    weight: "89",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "medium",
    ponyTail: "yes",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "curved",
    noseShape: "upturned",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/11-briggie-higgins.jpeg",
  },
  {
    id: "12",
    name: "Chris brown",
    age: "25",
    sex: "male",
    height: "160",
    weight: "65",
    hairType: "kinky",
    hairColour: "blonde",
    hairLength: "short",
    eyesColour: "black",
    glasses: "no",
    complexion: "olive skin",
    scars: "no",
    tattoos: "no",
    earShape: "narrow lobe",
    eyebrowsShape: "straight",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "long",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/12-chris_brown.jpeg",
  },
  {
    id: "13",
    name: "frank Sinatra",
    age: "30",
    sex: "female",
    height: "165",
    weight: "70",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "medium skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "straight",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/13-frank-sinatra.jpeg",
  },
  {
    id: "14",
    name: "john berg",
    age: "34",
    sex: "fmale",
    height: "190",
    weight: "82",
    hairType: "straight",
    hairColour: "brown",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "brown",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "straight",
    noseShape: "roman",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "square",
    neck: "short",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/14-john-berg.jpeg",
  },
  {
    id: "15",
    name: "jack nicholson",
    age: "45",
    sex: "male",
    height: "172",
    weight: "79",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "pointed ear",
    eyebrowsShape: "soft arch",
    noseShape: "roman",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/15-jack-nicholson.jpeg",
  },
  {
    id: "16",
    name: "John Kater",
    age: "24",
    sex: "male",
    height: "178",
    weight: "78",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "black skin",
    scars: "no",
    tattoos: "no",
    earShape: "sticking out",
    eyebrowsShape: "soft arch",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/16-john-kater.jpeg",
  },
  {
    id: "17",
    name: "Justin bieber",
    age: "17",
    sex: "male",
    height: "164",
    weight: "69",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "brown",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "none",
    earShape: "pointed ear",
    eyebrowsShape: "curved",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/17-justin-bieber.jpeg",
  },
  {
    id: "18",
    name: "Katt Williams",
    age: "30",
    sex: "male",
    height: "155",
    weight: "70",
    hairType: "straight ",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: " black skin ",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "igh arch",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/18-katt-williams.jpeg",
  },
  {
    id: "19",
    name: "richie brown",
    age: "20",
    sex: "male",
    height: "172",
    weight: "69",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: " black skin",
    scars: "no",
    tattoos: "yes",
    earShape: "attached lobe",
    eyebrowsShape: "straight",
    noseShape: "upturned",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "medium",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "yes",
    image: "/img/19-richie-brown.png",
  },
  {
    id: "20",
    name: "mick  jagger",
    age: "30",
    sex: "male",
    height: "165",
    weight: "55",
    hairType: "straight",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "short",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/20-mick-jagger.jpeg",
  },
  {
    id: "21",
    name: "peter rico",
    age: "30",
    sex: "male",
    height: "182",
    weight: "79",
    hairType: "kinky ",
    hairColour: "black",
    hairLength: "medium ",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "black skin ",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "upward ",
    noseShape: "button",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "no",
    image: "/img/21-peter-rico.png",
  },
  {
    id: "22",
    name: "mick taylor",
    age: "30",
    sex: "male",
    height: "180",
    weight: "85",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "brown skin",
    scars: "no",
    tattoos: "yes",
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: " black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "short",
    moustache: "yes",
    beard: "yes",
    goatee: "yes",
    sideburns: "no",
    image: "/img/22-mick-taylor.jpeg",
  },
  {
    id: "23",
    name: "steven tyler",
    age: "18",
    sex: "male",
    height: "165",
    weight: "60",
    hairType: "straight",
    hairColour: "back",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "straight",
    noseShape: "upturned",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/23-steven-tyler.jpeg",
  },
  {
    id: "24",
    name: "steven nolan",
    age: "25",
    sex: "male",
    height: "199",
    weight: "80",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "long",
    ponyTail: "no",
    eyesColour: "green",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "yes",
    earShape: "broad lobe",
    eyebrowsShape: "straight",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/24-steven-nolan.jpeg",
  },
  {
    id: "25",
    name: "jim butcher",
    age: "45",
    sex: "male",
    height: "181",
    weight: "84",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "blue",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "yes",
    earShape: "attached lobe",
    eyebrowsShape: "curved",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "square",
    neck: "short",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "no",
    image: "/img/25-jim-butcher.png",
  },
  {
    id: "26",
    name: "shane jacobs",
    age: "15",
    sex: "male",
    height: "145",
    weight: "55",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "brown",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "yes",
    earShape: "attached lobe",
    eyebrowsShape: "curved",
    noseShape: "button",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "short",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/26-shane-jacobs.jpeg",
  },
  {
    id: "27",
    name: "david frank",
    age: "27",
    sex: "male",
    height: "173",
    weight: "70",
    hairType: "straight",
    hairColour: "blackb",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "yes",
    earShape: "attached lobe",
    eyebrowsShape: "high arch",
    noseShape: "roman",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/27-david-frank.jpeg",
  },
  {
    id: "28",
    name: "lisa mitchell",
    age: "25",
    sex: "female",
    height: "166",
    weight: "72",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "black skin",
    scars: "non",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "high arch",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "long",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/28-lisa-mitchell.jpeg",
  },
  {
    id: "29",
    name: "richard zitch",
    age: "26",
    sex: "male",
    height: "165",
    weight: "76",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "brown",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "curved",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "yes",
    goatee: "no",
    sideburns: "no",
    image: "/img/29-richard-zitch.png",
  },
  {
    id: "30",
    name: "terrence howard",
    age: "32",
    sex: "male",
    height: "178",
    weight: "76",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "brown",
    glasses: "no",
    complexion: "brown skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "droopy",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "short",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/30-terrence-howard.jpeg",
  },
  {
    id: "31",
    name: "tim allen",
    age: "35",
    sex: "male",
    height: "170",
    weight: "76",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "long",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/31-tim-allen.jpeg",
  },
  {
    id: "32",
    name: "tupac shakur",
    age: "22",
    sex: "male",
    height: "165",
    weight: "68",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "black skin",
    scars: "no",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "curved",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "short",
    moustache: "yes",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/32-tupac-shakur.jpeg",
  },
  {
    id: "33",
    name: "rick station",
    age: "22",
    sex: "male",
    height: "175",
    weight: "71",
    hairType: "kinky",
    hairColour: "blondeblack",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "brown skin",
    scars: "no",
    tattoos: "yes",
    earShape: "pointed ear",
    eyebrowsShape: "straight",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "heartshape",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/33-rick-station.jpeg",
  },
  {
    id: "34",
    name: "razelmucha",
    age: "40",
    sex: "male",
    height: "176",
    weight: "80",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "no",
    tattoos: "no",
    earShape: "broadlobe",
    eyebrowsShape: "curved",
    noseShape: "roman",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "short",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/34-razel-mucha.jpeg",
  },
  {
    id: "35",
    name: "driken miller",
    age: "23",
    sex: "male",
    height: "176",
    weight: "70",
    hairType: "kinky",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "blackskin",
    scars: "no",
    tattoos: "no",
    earShape: "attachedlobe",
    eyebrowsShape: "curved",
    noseShape: "grecian",
    race: "black",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "medium",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "yes",
    image: "/img/35-driken-miller.jpeg",
  },
];

//];

// const done = 0;
// for (var i = 0; i < suspects.length; i++) {
//   suspects[i].save(function (err, result) {
//     done++;
//     if (done === suspects.length) {
//       exit();
//     }
//   });
// }

Suspect.insertMany(suspectSeed)
  .then(() => mongoose.disconnect())
  .catch((err) => console.log(err));

// db.suspects
//   .remove({})
//   .then(() => db.suspects.collection.insertMany(suspectSeed))
//   .then((data) => {
//     console.log(data.result.n + " records inserted!");
//     process.exit(0);
//   })
//   .catch((err) => {
//     console.error(err);
//     process.exit(1);
//   });
