const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Suspects collection and inserts the suspects below

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/suspects");

const suspectSeed = [
  {
    name: "linda pearl",
    age: "30",
    sex: "female",
    height: "165",
    weight: "170",
    hairType: "straight",
    hairColour: "blonde",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "extremely fair skin",
    scars: "none",
    tattoos: "no",
    earShape: "narrow lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "asian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "round",
    neck: "short",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/1-linda pearl.jpeg",
  },

  {
    name: "lorna james",
    age: "30",
    sex: "female",
    height: "165",
    weight: "170",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "fair skin",
    scars: "none",
    tattoos: no,
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/2-lorna-james.jpeg",
  },

  {
    name: "billie Kidd",
    age: "45",
    sex: "male",
    height: "180",
    weight: "175",
    hairType: "straight",
    hairColour: "black",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "extremely fair skin",
    scars: "none",
    tattoos: "no",
    earShape: "attached lobe",
    eyebrowsShape: "soft arch",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "no",
    goatee: "yes",
    sideburns: "no",
    image: "/img/3-billie-kidd.jpeg",
  },

  {
    name: "elli belle",
    age: "40",
    sex: "female",
    height: "173",
    weight: "180",
    hairType: "curly",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "yes",
    complexion: "fair skin",
    scars: "none",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "soft arch",
    noseShape: "hooked",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "diamond",
    neck: "short ",
    moustache: "no",
    beard: "no",
    goatee: "no",
    sideburns: "no",
    image: "/img/4-elli-belle.jpeg",
  },

  {
    name: "allan sutton",
    age: "45",
    sex: "male",
    height: "180",
    weight: "173",
    hairType: "curly",
    hairColour: "brown",
    hairLength: "short",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "none",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "curved",
    noseShape: "grecian",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "short",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "no",
    image: "/img/5-allan-sutton",
  },

  {
    name: "John Doe",
    age: "50",
    sex: "male",
    height: "185",
    weight: "190",
    hairType: "straight",
    hairColour: "black",
    hairLength: "medium",
    ponyTail: "no",
    eyesColour: "black",
    glasses: "no",
    complexion: "fair skin",
    scars: "none",
    tattoos: "no",
    earShape: "broad lobe",
    eyebrowsShape: "curved",
    noseShape: "aquiline",
    race: "caucasian",
    teethMissing: "no",
    wrinkles: "no",
    faceShape: "oval",
    neck: "medium",
    moustache: "yes",
    beard: "yes",
    goatee: "no",
    sideburns: "yes",
    image: "/img/6-john-doe.jpeg",
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];

const done = 0;
for (var i = 0; i <  suspects.length; i++)
{
  suspects[i].save(function(err,result){
    done++;
    if(done === suspects.length) {
      exit();
    }
  });
}
function exit() {
  mongoose.disconnect();
}


db.Suspect.remove({})
  .then(() => db.Suspect.collection.insertMany(suspectSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
