const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Suspects collection and inserts the suspects below

mongoose.connect(process.env.MONGODB_URI || "mongoose://localhost:27017/suspects");

const suspectSeed = [
  {
    "id": "1",
    "name": "linda pearl",
    "age": "30",
    "sex": "female",
    "height": "165",
    "weight": "170",
    "hairType": "straight",
    "hairColour": "blonde",
    "hairLength": "short",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "extremely fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "narrow lobe",
    "eyebrowsShape": "soft arch",
    "noseShape": "aquiline",
    "race": "asian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "round",
    "neck": "short",
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/1-linda pearl.jpeg",
  },


  {"id": "2",
    "name": "lorna james",
    "age": "30",
    "sex": "female",
    "height": "165",
    "weight": "170",
    "hairType": "straight",
    "hairColour": "black",
    "hairLength": "short",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "yes",
    "complexion": "fair skin",
    "scars": "no",
    "tattoos": no,
    "earShape": "attached lobe",
    "eyebrowsShape": "soft arch",
    "noseShape": "aquiline",
    "race": "caucasian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "medium",
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/2-lorna-james.jpeg",
  },

  {
    "id":"3",
    "name": "billie Kidd",
    "age": "45",
    "sex": "male",
    "height": "180",
    "weight": "175",
    "hairType": "straight",
    "hairColour": "black",
    "hairLength": "short",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "yes",
    "complexion": "extremely fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe",
    "eyebrowsShape": "soft arch",
    "noseShape": "aquiline",
    "race": "caucasian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "medium",
    "moustache": "yes",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/3-billie-kidd.jpeg",
  },

  {
    "id": "4",
    "name": "elli belle",
    "age": "40",
    "sex": "female",
    "height": "173",
    "weight": "180",
    "hairType": "curly",
    "hairColour": "black",
    "hairLength": "medium",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "yes",
    "complexion": "fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe",
    "eyebrowsShape": "soft arch",
    "noseShape": "hooked",
    "race": "caucasian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "diamond",
    "neck": "short ",
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/4-elli-belle.jpeg",
  },

  {
    "id": "5",
    "name": "allan sutton",
    "age": "45",
    "sex": "male",
    "height": "180",
    "weight": "173",
    "hairType": "curly",
    "hairColour": "brown",
    "hairLength": "short",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe",
    "eyebrowsShape": "curved",
    "noseShape": "grecian",
    "race": "caucasian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "short",
    "moustache": "yes",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/5-allan-sutton",
  },

  {"id": "6",
    "name": "John Doe",
    "age": "50",
    "sex": "male",
    "height": "185",
    "weight": "190",
    "hairType": "straight",
    "hairColour": "black",
    "hairLength": "medium",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe",
    "eyebrowsShape": "curved",
    "noseShape": "aquiline",
    "race": "caucasian",
    "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "medium",
    "moustache": "yes",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "yes",
    "image": "/img/6-john-doe.jpeg",
  },
  { "id": "7",
    "name":"rafa fraka",
    "age": "48",
    "sex": "male",
    "height": "190",
    "weight": "187",
    "hairType":  "curly", 
    "hairColour":"black", 
    "hairLength": "medium ",
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion":  "fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe", 
    "eyebrowsShape":  "high arch",  
    "noseShape": "roman", 
    "race":  "latino",
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "square",  
    "neck":  "long", 
    "moustache": "yes",
    "beard": "no",
    "goatee": "no",
    "sideburns": "yes",
    "image": "/img/7-rafa-fraka",
      },

  {"id": "8",
  "name":"curtis jackson",
  "age": "30",
  "sex": "male",
  "height": "176",
  "weight": "180",
  "hairType": "kinky", 
  "hairColour": "black", 
  "hairLength": "short",  
  "ponyTail": "no",
  "eyesColour":"black",
  "glasses": "no",
  "complexion":  "black skin", 
  "scars": "no",
  "tattoos": "no",
  "earShape":  "pointed ear",
  "eyebrowsShape":  "curved",   
  "noseShape": "button", 
  "race":  "black",
 "teethMissing": "no",
  "wrinkles": "no",
  "faceShape": "oval", 
  "neck":  "medium", 
  "moustache":"no",
  "beard": "no",
  "goatee": "no",
  "sideburns": "no",
  "image": "/img/8-curtis-jackson"
},
  {"id": "9",
    "name":"bill gates",
    "age": "29",
    "sex": "male",
    "height": "175",
    "weight": "163",
    "hairType": "straight", 
    "hairColour": "blonde", 
    "hairLength": "medium", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "yes",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "round lobe", 
    "eyebrowsShape":  "soft arch", 
    "noseShape": "roman",  
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "diamond" , 
    "neck":  "medium",  
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/9-bill-gates",

  },
  {"id": "10",
    "name":"bonnie parker",
    "age": "20",
    "sex": "male",
    "height": "166",
    "weight": "172",
    "hairType": "straight",
    "hairColour": "black", 
    "hairLength": "short",
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape":  "pointed ear", 
    "eyebrowsShape": "soft arch",  
    "noseShape": "aquiline", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval", 
    "neck":  "medium",  
    "moustache":"no",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/10-bonnie_parker",
      },
  {"id": "11",
    "name":"bridge higgins",
    "age": "28",
    "sex": "female",
    "height": "183",
    "weight": "179",
    "hairType": "straight", 
    "hairColour": "blonde", 
    "hairLength":  "medium",
    "ponyTail": "yes",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe",  
    "eyebrowsShape":  "curved", 
    "noseShape": "upturned",  
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "diamond", 
    "neck":  "long", 
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/11-briggie-higgins",
  },
  {"id": "12",
    "name":"Chris brown",
    "age": "25",
    "sex": "male",
    "height": "160",
    "weight": "165",
    "hairType": "kinky", 
    "hairColour": "blonde", 
    "hairLength": "short", 
    "eyesColour": "black",
    "glasses": "no",
    "complexion":  "olive skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape":  "narrow lobe", 
    "eyebrowsShape": "straight", 
    "noseShape": "roman",  
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "oval",  
    "neck": "long", 
    "moustache": "yes",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/12-chris_brown",

  },
  {"id": "13",
    "name":"frank Sinatra",
    "age": "30",
    "sex": "female",
    "height": "165",
    "weight": "170",
    "hairType": "straight",  
    "hairColour": "black", 
    "hairLength": "short",   
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "medium skin",  
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe", 
    "eyebrowsShape": "straight",  
    "noseShape": "aquiline", 
    "race": "caucasian", 
   "teethMissing":  "no",
    "wrinkles": "no",
    "faceShape": "diamond", 
    "neck": "long", 
    "moustache": "no",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/13-frank-sinatra",
  },
  {"id": "14",
    "name":"john berg",
    "age": "34",
    "sex": "fmale",
    "height": "190",
    "weight": "180",
    "hairType": "straight", 
    "hairColour": "brown", 
    "hairLength": "short",  
    "ponyTail": "no",
    "eyesColour":"brown",
    "glasses": "no",
    "complexion": "extremely fair skin",  
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe", 
    "eyebrowsShape": "straight", 
    "noseShape": "roman", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "square", 
    "neck": "short", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/14-john_berg",

  },
  {"id": "15",
    "name":"jack nicholson",
    "age": "45",
    "sex": "male",
    "height": "172",
    "weight": "179",
    "hairType": "straight",  
    "hairColour": "black", 
    "hairLength": "short",   
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion":  "fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "pointed ear",  
    "eyebrowsShape": "soft arch",  
    "noseShape": "roman", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "round", 
    "neck":  "medium", 
    "moustache":"no",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/15-jack-nicholson",

  },
  {"id": "16",
    "name":"John Kater",
    "age": "24",
    "sex": "male",
    "height": "178",
    "weight": "178",
    "hairType":  "kinky", 
    "hairColour": "black", 
    "hairLength": "short",    
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion":  "black skin",
    "scars": "no",
    "tattoos": "no",
    "earShape":  "sticking out", 
    "eyebrowsShape":  "soft arch", 
    "noseShape": "roman", 
    "race":  "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "diamond", 
    "neck":  "medium", 
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/16-john-kater",

  },
  {"id": "17",
    "name":"Justin bieber",
    "age": "17",
    "sex": "male",
    "height": "164",
    "weight": "169",
    "hairType": "straight",  
    "hairColour": "blonde", 
    "hairLength": "short",   
    "ponyTail": "no",
    "eyesColour": "brown",
    "glasses": "no",
    "complexion": "extremely fair skin",  
    "scars": "no",
    "tattoos": "none",
    "earShape": "pointed ear",  
    "eyebrowsShape":  "curved", 
    "noseShape": "aquiline",  
    "race": "caucasian",  
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "diamond", 
    "neck": "long",
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/17-justin-bieber",
  },
  {"id": "18",
    "name":"Katt Williams",
    "age": "30",
    "sex": "male",
    "height": "155",
    "weight": "170",
    "hairType": "straight ",
    "hairColour":  "black", 
    "hairLength": "short", 
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": " black skin ",
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe",
    "eyebrowsShape": "igh arch",
    "noseShape": "roman",
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval", 
    "neck": "medium", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/18-katt-williams",

  },
  {"id": "19",
    "name":"richie brown",
    "age": "20",
    "sex": "male",
    "height": "172",
    "weight": "169",
    "hairType":  "kinky", 
    "hairColour": "black", 
    "hairLength": "short",   
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": " black skin", 
    "scars": "no",
    "tattoos": "yes",
    "earShape": "attached lobe", 
    "eyebrowsShape": "straight", 
    "noseShape": "upturned", 
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "diamond" , 
    "neck": "medium", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "yes",
    "image": "/img/19-richie-brown",

  },
  {"id": "20",
    "name":"mick  jagger",
    "age": "30",
    "sex": "male",
    "height": "165",
    "weight": "55",
    "hairType": "straight",
    "hairColour": "black", 
    "hairLength": "medium", 
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached",
    "eyebrowsShape": "soft arch", 
    "noseShape": "aquiline", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "short", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/20-mick-jagger",

  },
  {"id": "21",
    "name":"peter rico",
    "age": "30",
    "sex": "male",
    "height": "182",
    "weight": "79",
    "hairType": "kinky ",
    "hairColour": "black", 
    "hairLength":  "medium ",
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": "black skin ",
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe", 
    "eyebrowsShape": "upward ",
    "noseShape": "button", 
    "race": "black",
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval" , 
    "neck": "medium", 
    "moustache":"yes",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/21-peter-rico",

  },
  {"id": "22",
    "name":"mick taylor",
    "age": "30",
    "sex": "male",
    "height": "180",
    "weight": "85",
    "hairType":  "kinky", 
    "hairColour": "black", 
    "hairLength": "short", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "brown skin", 
    "scars": "no",
    "tattoos": "yes",
    "earShape": "attached lobe", 
    "eyebrowsShape":  "soft arch", 
    "noseShape": "aquiline", 
    "race": " black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "diamond", 
    "neck": "short", 
    "moustache": "yes",
    "beard": "yes",
    "goatee": "yes",
    "sideburns": "no",
    "image": "/img/22-mick-taylor",

  },
  {"id": "23",
    "name": "steven tyler",
    "age": "18",
    "sex": "male",
    "height": "165",
    "weight": "60",
    "hairType": "straight",
    "hairColour": "back", 
    "hairLength":  "medium", 
    "ponyTail": "no",
    "eyesColour":"black",
    "glasses": "no",
    "complexion": "extremely fair", 
    "scars": "no",
    "tattoos": "no",
    "earShape":  "broad lobe", 
    "eyebrowsShape": "straight",
    "noseShape": "upturned", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval", 
    "neck": "medium",  
    "moustache": "no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/23-steven-tyler",
  },
  {"id": "24",
    "name":"steven nolan",
    "age": "25",
    "sex": "male",
    "height": "199",
    "weight": "80",
    "hairType": "straight", 
    "hairColour": "blonde", 
    "hairLength": "long",
    "ponyTail": "no",
    "eyesColour":"green",
    "glasses": "no",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "yes",
    "earShape":  "broad lobe", 
    "eyebrowsShape": "straight", 
    "noseShape":  "aquiline", 
    "race": "caucasian",
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval",
    "neck": "long", 
    "moustache":"no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/24-steven-nolan",
  },
  {"id": "25",
    "name":"jim butcher",
    "age": "45",
    "sex": "male",
    "height": "181",
    "weight": "84",
    "hairType": "straight", 
    "hairColour": "blonde", 
    "hairLength": "short", 
    "ponyTail": "no",
    "eyesColour": "blue",
    "glasses": "no",
    "complexion": "extremely fair skin",
    "scars": "no",
    "tattoos": "yes",
    "earShape": "attached lobe", 
    "eyebrowsShape": "curved", 
    "noseShape":  "aquiline", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "square", 
    "neck": "short", 
    "moustache": "yes",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/25-jim-butcher",

  },
  {"id": "26",
  "name":"shane jacobs",
  "age": "15",
  "sex": "male",
  "height": "145",
  "weight": "55",
  "hairType": "straight", 
  "hairColour": "blonde", 
  "hairLength": "short",   
  "ponyTail": no,
  "eyesColour":"brown",
  "glasses": "no",
  "complexion": "extremely fair skin",
  "scars": "no",
  "tattoos": "yes",
  "earShape": "attached lobe", 
  "eyebrowsShape": "curved", 
  "noseShape": "button", 
  "race": "caucasian", 
 "teethMissing": "no",
  "wrinkles": "no",
  "faceShape": "round", 
  "neck": "short",
  "moustache":"yes",
  "beard": "no",
  "goatee": "no",
  "sideburns": "no",
  "image": "/img/26-shane-jacobs",
},
  {"id": "27",
    "name":"david frank",
    "age": "27",
    "sex": "male",
    "height": "173",
    "weight": "70",
    "hairType": "straight", 
    "hairColour": "blackb", 
    "hairLength": "medium", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "yes",
    "earShape": "attached lobe",
    "eyebrowsShape": "high arch", 
    "noseShape": "roman", 
    "race": "caucasian", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "diamond", 
    "neck": "long", 
    "moustache":"no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/27-david-frank",
 
  },
  {"id": "28",
    "name":"lisa mitchell",
    "age": "25",
    "sex": "female",
    "height": "166",
    "weight": "172",
    "hairType": "kinky",
    "hairColour": "black", 
    "hairLength": "short", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "black skin",
    "scars": "non",
    "tattoos": "no",
    "earShape": "attached lobe", 
    "eyebrowsShape": "high arch",
    "noseShape": "roman",
    "race":  "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "round", 
    "neck": "long", 
    "moustache":"no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/28-lisa-mitchell",

  },
  {"id": "29",
    "name":"richard zitch",
    "age": "26",
    "sex": "male",
    "height": "165",
    "weight": "76",
    "hairType": "kinky", 
    "hairColour": "black", 
    "hairLength": "short",   
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "brown",
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe",
    "eyebrowsShape": "curved", 
    "noseShape":"roman", 
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "oval", 
    "neck": "medium", 
    "moustache":"no",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/29-richard-zitch",

  },
  {"id": "30",
    "name":"terrence howard",
    "age": "32",
    "sex": "male",
    "height": "178",
    "weight": "76",
    "hairType":  "kinky", 
    "hairColour": "black", 
    "hairLength": "short", 
    "ponyTail": "no",
    "eyesColour": "brown",
    "glasses": "no",
    "complexion": "brown skin",  
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe", 
    "eyebrowsShape": "soft arch", 
    "noseShape": "droopy", 
    "race":  "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "oval", 
    "neck": "short", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/30-terrence-howard",
  },
  {"id": "31",
    "name":"tim allen",
    "age": "35",
    "sex": "male",
    "height": "170",
    "weight": "76",
    "hairType": "straight", 
    "hairColour": "black", 
    "hairLength": "short",  
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "extremely fair skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "broad lobe", 
    "eyebrowsShape":  "soft arch", 
    "noseShape": "aquiline",
    "race": "caucasian", 
    "wrinkles": "no",
    "faceShape": "diamond", 
    "neck":  "long", 
    "moustache":"yes",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/31-tim-allen",

  },
  {"id": "32",
    "name":"tupac shakur",
    "age": "22",
    "sex": "male",
    "height": "165",
    "weight": "68",
    "hairType": "kinky", 
    "hairColour": "black", 
    "hairLength": "short",  
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "black skin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "attached lobe", 
    "eyebrowsShape":  "curved", 
    "noseShape": "roman", 
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "oval", 
    "neck": "short", 
    "moustache": "yes",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/32-tupac-shakur",

  },
  {"id": "33",
    "name":"rick station",
    "age": "22",
    "sex": "male",
    "height": "175",
    "weight": "71",
    "hairType":  "kinky", 
    "hairColour":  "blondeblack", 
    "hairLength": "medium", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "brown skin", 
    "scars": "no",
    "tattoos": "yes",
    "earShape": "pointed ear", 
    "eyebrowsShape": "straight",
    "noseShape": "roman", 
    "race":  "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "heartshape", 
    "neck": "medium",  
    "moustache":"no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/33-rick-station",

  },
  {"id": "34",
    "name":"razelmucha",
    "age": "40",
    "sex": "male",
    "height": "176",
    "weight": "80",
    "hairType": "kinky", 
    "hairColour": "black", 
    "hairLength": "medium", 
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "fair skin",
    "scars": "no",
    "tattoos": "no",
    "earShape":  "broadlobe", 
    "eyebrowsShape":  "curved", 
    "noseShape": "roman", 
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape": "round", 
    "neck": "short", 
    "moustache":"no",
    "beard": "no",
    "goatee": "no",
    "sideburns": "no",
    "image": "/img/34-razel-mucha",

  },
  {"id": "35",
    "name":"driken miller",
    "age": "23",
    "sex": "male",
    "height": "176",
    "weight": "70",
    "hairType":  "kinky", 
    "hairColour": "black", 
    "hairLength": "medium",   
    "ponyTail": "no",
    "eyesColour": "black",
    "glasses": "no",
    "complexion": "blackskin", 
    "scars": "no",
    "tattoos": "no",
    "earShape": "attachedlobe", 
    "eyebrowsShape":  "curved",
    "noseShape": "grecian", 
    "race": "black", 
   "teethMissing": "no",
    "wrinkles": "no",
    "faceShape":  "diamond", 
    "neck":  "medium",  
    "moustache": "yes",
    "beard": "yes",
    "goatee": "no",
    "sideburns": "yes",
    "image": "/img/35-driken-miller",
  },
 
];

const done = 0;
for (var i = 0; i <  suspects.length; i++)
{
  suspects[i].save(function(err,result){
    done++;
    if(done === suspects.length) {
      exit();
    }
  });
}
function exit() {
  mongoose.disconnect();
}


db.suspects.remove({})
  .then(() => db.suspects.collection.insertMany(suspectSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
